"""
fathom_slack_canvas_agent

Creates a Slack Canvas from Fathom call summary, tags owners, and sets reminders.

Generated by V1 Meta-Agent
"""

from google.adk.agents import Agent
from .fathom_tools import recieve_fathom_webhook
from .slack_tools import get_user_by_email, create_meeting_notes_canvas, create_task_reminder

root_agent = Agent(
    name="fathom_slack_canvas_agent",
    model="gemini-1.5-flash",
    description="""Creates a Slack Canvas from Fathom call summary, tags owners, and sets reminders.""",
    instruction="""
1. Receive Fathom webhook payload using recieve_fathom_webhook.
2. Extract things_discussed and key_actions (with owner_email and optional due_date) from the payload.
3. For each owner in key_actions, use get_user_by_email to find their Slack User ID.
4. Call create_meeting_notes_canvas to generate the Canvas in the target channel, structuring the output with Things Discussed and Action Items (using the retrieved Slack IDs for tagging).
5. For each action item, call create_task_reminder to set a reminder for the assigned owner using the extracted due_date (or a default if missing).
6. Post a confirmation message in the channel: "Fathom call summary and action items have been added to the Canvas. Reminders set for each owner."

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        recieve_fathom_webhook, get_user_by_email, create_meeting_notes_canvas, create_task_reminder
    ]
)
