"""
fathom_to_slack_automation

Automates the creation of Slack Canvas and reminders from Fathom call summaries.

Generated by V1 Meta-Agent
"""

from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from .fathom_tools import fetch_fathom_call_summary
from .slack_tools import create_meeting_notes_canvas, get_user_by_email, create_task_reminder

root_agent = Agent(
    name="fathom_to_slack_automation",
    # model="gemini-2.0-flash",
    model=LiteLlm(model="openai/gpt-4o"),
    description="""Automates the creation of Slack Canvas and reminders from Fathom call summaries.""",
    instruction="""
1. Fetch call summary from Fathom API using call_id. 2. Extract 'things_discussed' and 'key_actions' with owner names. 3. Create a Slack Canvas in the client's shared channel. 4. Convert each owner name to a Slack @mention using 'get_user_by_email'. 5. Set reminders for each task using 'create_task_reminder'. 6. Post a confirmation message in the Slack channel.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        fetch_fathom_call_summary, create_meeting_notes_canvas, get_user_by_email, create_task_reminder
    ]
)
