"""
fathom_to_slack_agent

Automates the creation of Slack Canvas from Fathom call summaries, tagging owners and setting reminders.

Generated by V1 Meta-Agent
"""

from google.adk.agents import Agent
from .fathom_tools import recieve_fathom_webhook, fetch_fathom_call_summary
from .slack_tools import create_meeting_notes_canvas, create_task_reminder, get_user_id_from_email

root_agent = Agent(
    name="fathom_to_slack_agent",
    model="gemini-1.5-flash",
    description="""Automates the creation of Slack Canvas from Fathom call summaries, tagging owners and setting reminders.""",
    instruction="""
1. Receive Fathom call-end webhook and extract necessary fields: things_discussed, key_actions with owner names.
2. Determine the Slack channel shared with the client using predefined mapping or metadata.
3. Create or update a Slack Canvas in the specified channel. Structure it with a 'Things Discussed' section and 'Action Items' section.
4. For each action owner, convert owner_name to a Slack @mention if the user exists, else leave as plain text.
5. Set Slack reminders for each task to notify users directly. Use provided due_date or default to 2 days.
6. Post a confirmation message in the channel indicating the Canvas update and reminders set.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        recieve_fathom_webhook, fetch_fathom_call_summary, create_meeting_notes_canvas, create_task_reminder, get_user_id_from_email
    ]
)
