"""
hubspot_notion_slack_deal_workflow

Agent for managing deal stages across HubSpot, Notion, and Slack

Generated by V1 Meta-Agent
"""

import os
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from .hubspot_tools.get_deal_data import get_deal_data
from .notion_tools.create_page import create_page
from .notion_tools.append_to_notion_page import append_to_notion_page
from .notion_tools.delete_notion_page import delete_notion_page
from .slack_tools.create_meeting_notes_canvas import create_meeting_notes_canvas
from .slack_tools.send_scheduled_direct_message import send_scheduled_direct_message
from .slack_tools.create_task_reminder import create_task_reminder

# Load model from environment or use default
model_name = os.getenv("AGENT_MODEL", "openai/gpt-4o")

root_agent = Agent(
    name="hubspot_notion_slack_deal_workflow",
    model=LiteLlm(model=model_name),
    description="""Agent for managing deal stages across HubSpot, Notion, and Slack""",
    instruction="""
1. User provides a deal ID to start the workflow
2. Retrieve deal data from HubSpot using get_deal_data
3. If the deal stage is 'Proposal started', create a Notion page with create_page and add the deal name as title and the current stage
4. Create a task in Slack Canvas using create_meeting_notes_canvas with the deal name as task title
5. If the deal stage is 'Lost', send a message to Slack channel and remove task from Canvas
6. If the deal stage is 'Won', update the Notion page status using append_to_notion_page and send a congratulatory message on Slack

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        get_deal_data, create_page, append_to_notion_page, delete_notion_page, create_meeting_notes_canvas, send_scheduled_direct_message, create_task_reminder
    ]
)
