"""
fathom_to_slack_canvas

Automation to create a Slack Canvas from manually inputted Fathom payload and set reminders for action items.

Generated by V1 Meta-Agent
"""

from google.adk.agents import Agent
from .fathom_tools import process_user_fathom_payload
from .slack_tools import create_meeting_notes_canvas, get_user_id_from_email, create_task_reminder, send_scheduled_direct_message

root_agent = Agent(
    name="fathom_to_slack_canvas",
    model="gemini-1.5-flash",
    description="""Automation to create a Slack Canvas from manually inputted Fathom payload and set reminders for action items.""",
    instruction="""
1. Parse the provided Fathom payload to extract things_discussed and key_actions.
2. Identify the Slack channel using predefined mapping or metadata.
3. Create a Slack Canvas in the identified channel with sections for Things Discussed and Action Items, tagging owners.
4. Convert owner names to Slack @mentions; if not found, keep as plain text.
5. Set reminders for each action item using due_date or default to 2 days from now.
6. Post a confirmation message in the channel about the creation and reminders.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        process_user_fathom_payload, create_meeting_notes_canvas, get_user_id_from_email, create_task_reminder, send_scheduled_direct_message
    ]
)
