"""
hubspot_notion_slack_agent

Agent manages deal stages using HubSpot, Notion, and Slack for notifications and task management.

Generated by V1 Meta-Agent
"""

import os
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from .hubspot_tools.get_deal_data import get_deal_data
from .notion_tools.create_page import create_page
from .notion_tools.append_to_notion_page import append_to_notion_page
from .slack_tools.create_meeting_notes_canvas import create_meeting_notes_canvas
from .slack_tools.send_scheduled_direct_message import send_scheduled_direct_message

# Load model from environment or use default
model_name = os.getenv("AGENT_MODEL", "openai/gpt-4o")

root_agent = Agent(
    name="hubspot_notion_slack_agent",
    model=LiteLlm(model=model_name),
    description="""Agent manages deal stages using HubSpot, Notion, and Slack for notifications and task management.""",
    instruction="""
1. When a deal's stage changes to 'Proposal Started' in HubSpot, fetch deal data using get_deal_data.
2. Create a Notion page with the deal name and stage using create_page.
3. Use create_meeting_notes_canvas to assign a task for the deal in Slack Canvas.
4. If the deal is marked 'Lost', notify the team using send_scheduled_direct_message and remove tasks.
5. If the deal is marked 'Won', update the Notion page status to 'Deal Won' using append_to_notion_page and notify team with send_scheduled_direct_message.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        get_deal_data, create_page, append_to_notion_page, create_meeting_notes_canvas, send_scheduled_direct_message
    ]
)
