"""
fathom_slack_canvas_agent_2

Processes Fathom meeting output and creates a Slack Canvas with action items, tags owners, and sets reminders.

Generated by V1 Meta-Agent
"""

import os
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from .fathom_tools import process_user_fathom_payload
from .slack_tools import create_meeting_notes_canvas, get_user_by_email, create_task_reminder

# Load model from environment or use default
model_name = os.getenv("AGENT_MODEL", "openai/gpt-4o")

root_agent = Agent(
    name="fathom_slack_canvas_agent_2",
    model=LiteLlm(model=model_name),
    description="""Processes Fathom meeting output and creates a Slack Canvas with action items, tags owners, and sets reminders.""",
    instruction="""
1. Parse provided Fathom meeting payload to extract 'things_discussed' and 'key_actions'.
2. Identify the Slack channel using predefined mappings or metadata.
3. Create a Slack Canvas in the identified channel including 'Things Discussed' and action items with owner details.
4. Convert owner names to Slack @mentions.
5. Set Slack reminders for each action item owner, based on 'due_date' or default to 2 days.
6. Post a confirmation message in the shared Slack channel.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        process_user_fathom_payload, create_meeting_notes_canvas, get_user_by_email, create_task_reminder
    ]
)
