"""
fathom_slack_canvas_automation

Automates the creation of a Slack Canvas from a manually inputted Fathom meeting payload.

Generated by V1 Meta-Agent
"""

from google.adk.agents import Agent
from .fathom_tools import process_user_fathom_payload
from .slack_tools import create_meeting_notes_canvas, get_user_id_from_email, create_task_reminder


root_agent = Agent(
    name="fathom_slack_canvas_automation",
    model="gemini-2.0-flash",
    description="""Automates the creation of a Slack Canvas from a manually inputted Fathom meeting payload.""",
    instruction="""
1. Parse the manually provided Fathom payload to extract things_discussed and key_actions.
2. Use predefined channel mapping or metadata to identify the Slack channel.
3. Create a Slack Canvas in the identified channel with things_discussed and key_actions.
4. Convert owner names to Slack mentions using their email.
5. Set reminders for each action item using the owner's email, defaulting to '2 days from now' if no due_date exists.
6. Post a confirmation message in the channel indicating completion of the process.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        process_user_fathom_payload, create_meeting_notes_canvas, get_user_id_from_email, create_task_reminder
    ]
)


