"""
deal_stage_agent

An agent to manage deal stages and perform actions in HubSpot, Notion, and Slack/Canvas based on deal stage changes.

Generated by V1 Meta-Agent
"""

import os
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from .hubspot_tools.get_deal_data import get_deal_data
from .notion_tools.create_notion_page import create_notion_page
from .notion_tools.append_to_notion_page import append_to_notion_page
from .slack_tools.create_meeting_notes_canvas import create_meeting_notes_canvas
from .slack_tools.send_scheduled_direct_message import send_scheduled_direct_message
from .slack_tools.get_user_id_from_email import get_user_id_from_email
from .slack_tools.get_user_by_email import get_user_by_email

# Load model from environment or use default
model_name = os.getenv("AGENT_MODEL", "openai/gpt-4o")

root_agent = Agent(
    name="deal_stage_agent",
    model=LiteLlm(model=model_name),
    description="""An agent to manage deal stages and perform actions in HubSpot, Notion, and Slack/Canvas based on deal stage changes.""",
    instruction="""
1. When a deal stage changes in HubSpot (triggers with deal ID provided by the user):

A. Initial Stage: Proposal Started
- Trigger: Deal stage set to 'Proposal started'.
- Action (Notion): Create a new page with the deal name as the title, noting stage ('Proposal started'), date, and time.
- Action (Slack/Canvas): Create a task in Canvas with the deal name and assign to designated team member.

B. Deal Outcome: Deal Lost
- Trigger: Deal stage set to 'Lost'.
- Action (Slack): Announce 'Deal Lost' in Slack channel.
- Action (Slack/Canvas): Remove task and associated documents in Canvas.

C. Deal Outcome: Deal Won
- Trigger: Deal stage set to 'Won'.
- Action (Notion): Update existing page status to 'Deal Won' and record date/time.
- Action (Slack): Announce 'Success' in Slack channel.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        get_deal_data, create_notion_page, append_to_notion_page, create_meeting_notes_canvas, send_scheduled_direct_message, get_user_id_from_email, get_user_by_email
    ]
)
