"""
hubspot_notion_slack_deal_agent

Manages deal stages across HubSpot, Notion, and Slack, handling proposal start, deal loss, and deal won scenarios

Generated by V1 Meta-Agent
"""

import os
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from .hubspot_tools.get_deal_data import get_deal_data
from .notion_tools.create_page import create_page
from .notion_tools.append_to_notion_page import append_to_notion_page
from .slack_tools.send_scheduled_direct_message import send_scheduled_direct_message

# Load model from environment or use default
model_name = os.getenv("AGENT_MODEL", "openai/gpt-4o")

root_agent = Agent(
    name="hubspot_notion_slack_deal_agent",
    model=LiteLlm(model=model_name),
    description="""Manages deal stages across HubSpot, Notion, and Slack, handling proposal start, deal loss, and deal won scenarios""",
    instruction="""
1. Fetch the deal data from HubSpot using the deal ID.
2. If the deal stage is 'Proposal Started', create a Notion page and a task in Slack Canvas.
3. If the deal stage is 'Lost', send a notification in Slack and remove the task from Canvas.
4. If the deal stage is 'Won', update the Notion page and send a success message in Slack.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        get_deal_data, create_page, append_to_notion_page, send_scheduled_direct_message
    ]
)
