"""
slack_scheduled_message_agent

Posts scheduled messages to Slack users.

Generated by V1 Meta-Agent
"""

import os
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from .slack_tools.send_scheduled_direct_message import send_scheduled_direct_message

# Load model from environment or use default
model_name = os.getenv("AGENT_MODEL", "openai/gpt-4o")

root_agent = Agent(
    name="slack_scheduled_message_agent",
    model=LiteLlm(model=model_name),
    description="""Posts scheduled messages to Slack users.""",
    instruction="""
1. Accept user email, message, and scheduled time.
2. Use send_scheduled_direct_message tool to schedule the message.
3. Automatically adjusts the scheduled time if it's in the past.
4. Sends the message to the specified user's email via Slack.

Always follow this workflow step-by-step and provide clear feedback after each action.
""",
    tools=[
        send_scheduled_direct_message
    ]
)
